name = "Newb X Judo"
version = [0, 0, 21]
min_supported_mc_version = [1, 20, 80]
url = "https://devendrn.github.io/newb-shader/"
authors = ["devendrn", "judohippo"]
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[description]
# %w = patch warning, %v = version
long = '''
ยงc%w
ยง7- An enchanced vanilla shader for Minecraft!
%v
ยง3https://devendrn.github.io/newb-shader/
'''
short = "Legacy port of Newb Shader for RenderDragon"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "dccd0e41-2d80-4b38-aca6-c9d038640ddc"
module = "25bd9855-7f55-40bc-bedb-964db790fa83"

[info]
# %a = authors
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
'''
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default


[[subpack]]
define = "Default"
materials =[]
description = '''
Default
'''
